#4 pipeline

diff --git a/.github/workflows/python-linting.yml b/.github/workflows/python-linting.yml
--- a/.github/workflows/python-linting.yml
+++ b/.github/workflows/python-linting.yml
@@ -27,11 +27,14 @@ jobs:
     - name: Run unit tests
       run: python -m unittest discover -s tests -p 'test_*.py'
 
+    - name: Run Ruff
+      run: ruff check --output-format=github src
+
     - name: Run Ruff and check for errors
       run: |
-        ruff_output=$(ruff src)
+        ruff_output=$(ruff check src)
         echo "$ruff_output"
-        error_count=$(echo "$ruff_output" | grep -c "error")
-        if (( error_count > 0 )); then
-          exit 1
-        fi
+        # error_count=$(echo "$ruff_output" | grep -c "error")
+        # if (( error_count > 0 )); then
+        #   exit 1
+        # fi
